steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 't','grc.io/gcp-project-363400/my-iris-app',]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'grc.io/gcp-project-363400/my-iris-app',]